-- Generated by modules/mod-coa/tools/generate_reaper.py; WoW 12.1.0.69814.
-- Only empty or byte-equivalent owned rows are accepted. Every data write is atomic.
DROP PROCEDURE IF EXISTS `coa_reaper_20260925_world`;
DELIMITER $$
CREATE PROCEDURE `coa_reaper_20260925_world`()
BEGIN
  DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
  START TRANSACTION;
  IF EXISTS (SELECT 1 FROM `spell_script_names` WHERE ((`spell_id` <=> 600000) OR (`spell_id` <=> 600001) OR (`spell_id` <=> 600002) OR (`spell_id` <=> 600003) OR (`spell_id` <=> 600006) OR (`spell_id` <=> 600007)) AND NOT ((`spell_id` <=> 600000 AND `ScriptName` <=> 'spell_coa_reaper_combat') OR (`spell_id` <=> 600001 AND `ScriptName` <=> 'spell_coa_reaper_combat') OR (`spell_id` <=> 600002 AND `ScriptName` <=> 'spell_coa_reaper_combat') OR (`spell_id` <=> 600003 AND `ScriptName` <=> 'spell_coa_reaper_combat') OR (`spell_id` <=> 600006 AND `ScriptName` <=> 'spell_coa_reaper_souls') OR (`spell_id` <=> 600007 AND `ScriptName` <=> 'spell_coa_reaper_souls'))) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Reaper conflict in spell_script_names; nothing changed';
  END IF;
  IF EXISTS (SELECT 1 FROM `spell_custom_attr` WHERE ((`entry` <=> 600005) OR (`entry` <=> 600006) OR (`entry` <=> 600007)) AND NOT ((`entry` <=> 600005 AND `attributes` <=> 16777216) OR (`entry` <=> 600006 AND `attributes` <=> 16777216) OR (`entry` <=> 600007 AND `attributes` <=> 16777216))) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Reaper conflict in spell_custom_attr; nothing changed';
  END IF;
  INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) SELECT 600000,'spell_coa_reaper_combat' WHERE NOT EXISTS (SELECT 1 FROM `spell_script_names` WHERE `spell_id` <=> 600000 AND `ScriptName` <=> 'spell_coa_reaper_combat');
  INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) SELECT 600001,'spell_coa_reaper_combat' WHERE NOT EXISTS (SELECT 1 FROM `spell_script_names` WHERE `spell_id` <=> 600001 AND `ScriptName` <=> 'spell_coa_reaper_combat');
  INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) SELECT 600002,'spell_coa_reaper_combat' WHERE NOT EXISTS (SELECT 1 FROM `spell_script_names` WHERE `spell_id` <=> 600002 AND `ScriptName` <=> 'spell_coa_reaper_combat');
  INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) SELECT 600003,'spell_coa_reaper_combat' WHERE NOT EXISTS (SELECT 1 FROM `spell_script_names` WHERE `spell_id` <=> 600003 AND `ScriptName` <=> 'spell_coa_reaper_combat');
  INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) SELECT 600006,'spell_coa_reaper_souls' WHERE NOT EXISTS (SELECT 1 FROM `spell_script_names` WHERE `spell_id` <=> 600006 AND `ScriptName` <=> 'spell_coa_reaper_souls');
  INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) SELECT 600007,'spell_coa_reaper_souls' WHERE NOT EXISTS (SELECT 1 FROM `spell_script_names` WHERE `spell_id` <=> 600007 AND `ScriptName` <=> 'spell_coa_reaper_souls');
  INSERT INTO `spell_custom_attr` (`entry`,`attributes`) SELECT 600005,16777216 WHERE NOT EXISTS (SELECT 1 FROM `spell_custom_attr` WHERE `entry` <=> 600005 AND `attributes` <=> 16777216);
  INSERT INTO `spell_custom_attr` (`entry`,`attributes`) SELECT 600006,16777216 WHERE NOT EXISTS (SELECT 1 FROM `spell_custom_attr` WHERE `entry` <=> 600006 AND `attributes` <=> 16777216);
  INSERT INTO `spell_custom_attr` (`entry`,`attributes`) SELECT 600007,16777216 WHERE NOT EXISTS (SELECT 1 FROM `spell_custom_attr` WHERE `entry` <=> 600007 AND `attributes` <=> 16777216);
  COMMIT;
END$$
DELIMITER ;
CALL `coa_reaper_20260925_world`();
DROP PROCEDURE `coa_reaper_20260925_world`;
